name: Publish
on:
  pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          show-progress: false
      - uses: pnpm/action-setup@v5
        name: Configure PNPM
      - name: Setup node env 🏗
        uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
          cache: 'pnpm'
      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile
      - name: Lint check ✅
        run: pnpm lint
      - name: Tests 🧑‍🔬
        run: pnpm test
      - name: Deploy 😎
        run: pnpm generate
