name: Update Indexes
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1-5'

jobs:
  update-market-data:
    permissions:
      contents: write
    name: Update market data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          show-progress: false
      - uses: pnpm/action-setup@v6.0.10
        name: Configure PNPM
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          check-latest: true
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Update market-data.json
        run: pnpm update-indexes
      - name: Checking for changes
        id: check_changes
        run: |
          if git diff --exit-code app/assets/market-data.json; then
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "has_changes=true" >> $GITHUB_ENV
          fi
      - name: Commit and push changes
        id: commit-and-push
        if: ${{ env.has_changes == 'true' }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add app/assets/market-data.json
          git commit -m "chore(market): update rates and projections"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
